[pazsalvo]
user = pazsalvo
group = pazsalvo
listen = /run/php/php-fpm-pazsalvo.sock
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 20
pm.start_servers = 4
pm.min_spare_servers = 2
pm.max_spare_servers = 6
pm.max_requests = 500
php_admin_value[open_basedir] = /var/www/PazSalvo:/tmp
php_admin_value[upload_tmp_dir] = /tmp
php_admin_value[sys_temp_dir] = /tmp
php_admin_value[memory_limit] = 256M
php_admin_value[max_execution_time] = 120
php_admin_value[post_max_size] = 10M
php_admin_value[upload_max_filesize] = 5M
php_admin_value[expose_php] = Off
php_admin_value[opcache.enable] = 1
php_admin_value[opcache.validate_timestamps] = 0
